services:
  db:
    image: postgres:15
    container_name: uniqiita-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uni_qiita
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uni_qiita"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniqiita-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/uni_qiita
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: http://localhost:8000/auth/callback
      ALLOWED_DOMAIN: u-aizu.ac.jp
      # ▼ 追加：Firebase Admin にサービスアカウントを渡す
      FIREBASE_CREDENTIALS_FILE: /run/secrets/firebase_sa.json
      # （必要なら）フロントのベースURLやセッション名
      FRONTEND_BASE: http://localhost:3000
      SESSION_COOKIE_NAME: session
    volumes:
      - .:/app
      # ▼ 追加：サービスアカウントJSONを read-only でマウント
      - ./secrets/firebase_sa.json:/run/secrets/firebase_sa.json:ro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data: