services: #動かすアプリやコンテナの一覧」を定義するブロック。例えばdb backend frontend とか書くとそれぞれのコンテナができる。docker compose up で立ち上げられる。
  db: #なぜ必要？他のサービス（例: backend）から「DBに接続したい！」とするときに、ホスト名 db で通信できる。
    image: postgres:15 #vesrionの固定
    container_name: uniqiita-db #コンテナの名前
  #postgersとはPostgreSQLというものでざっくりいうとExcelの強化版みたいなもの。データ表を管理するソフトみたいなイメージ
  #enviroment のなかにはpostgresがはいってるけどmysqlだとかでもいい

    environment: #何のためにあるんだろ
      POSTGRES_USER: postgres #初期ユーザーめい
      POSTGRES_PASSWORD: postgres #初期パスワード
      POSTGRES_DB: uni_qiita #初回起動時に自動作成するデータベース
    ports:
      - "5432:5432"   #ポートの橋渡しmacからdbにアクセスできるようにする
    volumes:
      - db_data:/var/lib/postgresql/data #:のdb_data 右はコンテナのディレクトリめい　:の左は名前付きvolume ? 右はコンテナの中のフォルダと、ホスト側の永続ストレージを紐づける。 データの倉庫的なやつ
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uni_qiita"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes: #これは (1) で指定した db_data を名前付きボリュームとして定義しているだけ。
  db_data:
