"""create article_tags table

Revision ID: 9bb182dbbf8b
Revises: 8c83d58b628c
Create Date: 2025-08-28 07:42:23.795194+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb182dbbf8b'
down_revision: Union[str, Sequence[str], None] = '8c83d58b628c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('article_id', 'tag_id', name='uq_article_tag')
    )
    op.create_index('ix_article_tags_article_id', 'article_tags', ['article_id'], unique=False)
    op.create_index('ix_article_tags_tag_id', 'article_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_tags_tag_id', table_name='article_tags')
    op.drop_index('ix_article_tags_article_id', table_name='article_tags')
    op.drop_table('article_tags')
    # ### end Alembic commands ###
